name: CI pipiline for GO-Web-APP

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
  
jobs:

  build:
    runs-on: ubuntu-latest  

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Go 1.22
    uses: actions/setup-go@v2
    with:
      go-version: 1.22
  
  - name: Build
    run: go build -o go-web-app
  
  - name: Test
    run: go test ./...
  

  code-quality:
    runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Run golangci-lint
    uses: golangci/golangci-lint-action@v6
    with:
      version: v1.56.2

jobs:
  push:

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME}}/go-web-app:${{github.run_id}}
  
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
    
    - name: Updating tag in Helm chart 
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

    - name: Commit an Push changes
      run: |
        git config --global user.email "manoj@gmail.com"
        git config --global user.name "Manoj Tiwari"
        git add helm/go-web-app-chart/values.yaml
        git Commit -m "Update tag in Helm chart"
        git push
